-- Example your-custom-config.lua
-- If you just want to configure items

CONFIG = {}
CONFIG.name = "spv3" -- YOU MUST NAME IT! Used for horde_external_lua_config.
CONFIG.items = {
	drc_br85={
		secondary_ammo_price=0.0,
		price=350.0,
		category="Rifle",
		class="drc_br85",
		entity_properties={type=1.0},
		ammo_price=70.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Survivor=true,Medic=true,Heavy=true,Engineer=true,Assault=true},
		cmp=350.0,
		name="Battle Rifle",
		description=""
	},
	drc_focusrifle={
		secondary_ammo_price=0.0,
		price=1200.0,
		category="Rifle",
		class="drc_focusrifle",
		entity_properties={type=1.0},
		ammo_price=999999.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=2000.0,
		name="Focus Rifle",
		description=""
	},
	drc_biofoam={
		secondary_ammo_price=0.0,
		price=500.0,
		category="Equipment",
		class="drc_biofoam",
		entity_properties={type=1.0},
		ammo_price=99999.0,
		weight=0.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=500.0,
		name="Biofoam",
		description="Medical biofoam which can be used for healing.\n IMPORTANT NOTE: Only heals 25hp and has 4 uses. Drop before obtaining another."
	},
	npc_vj_halo_unsc_spv3_pelican_turret={
		secondary_ammo_price=0.0,
		price=750.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_pelican_turret",
		entity_properties={
			x=50.0,type=3.0,
			limit=3.0,
			yaw=0.0,
		z=15.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=750.0,
		whitelist={Ghost=true,Demolition=true,Survivor=true,Medic=true,Heavy=true,Engineer=true,
		Assault=true},
		name="Ceiling Turret",
		description="A gatling ceiling turret which fires in a rapid manner at the target."
	},
	drc_plasma_rifle={
		secondary_ammo_price=0.0,
		price=450.0,
		category="SMG",
		class="drc_plasma_rifle",
		entity_properties={type=1.0},
		ammo_price=999999.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="Plasma Rifle",
		description=""
	},
	npc_vj_halo_unsc_spv3_johnson={
		secondary_ammo_price=0.0,
		price=750.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_johnson",
		entity_properties={
			x=50.0,type=3.0,
			yaw=0.0,
			z=15.0,
		limit=1.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=750.0,
		whitelist={Ghost=true,Demolition=true,Survivor=true,Medic=true,Heavy=true,Engineer=true,
		Assault=true},
		name="Sgt. Johnson",
		description="Often equipped with good armor and a shotgun, Johnson \nwill serve great in tight corners."
	},
	drc_m90_ce={
		secondary_ammo_price=0.0,
		price=600.0,
		category="Shotgun",
		class="drc_m90_ce",
		entity_properties={type=1.0},
		ammo_price=300.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=600.0,
		name="M90",
		description=""
	},
	drc_needler={
		secondary_ammo_price=0.0,
		price=300.0,
		category="SMG",
		class="drc_needler",
		entity_properties={type=1.0},
		ammo_price=60.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=300.0,
		name="Needler",
		description=""
	},
	drc_srs99c={
		secondary_ammo_price=0.0,
		price=600.0,
		category="Rifle",
		class="drc_srs99c",
		entity_properties={type=1.0},
		ammo_price=300.0,
		weight=7.0,
		cmp=600.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="SRS99C Sniper Rifle",
		description=""
	},
	npc_vj_halo_unsc_spv3_marine={
		secondary_ammo_price=0.0,
		price=250.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_marine",
		entity_properties={
			x=50.0,type=3.0,
			z=15.0,
			yaw=0.0,
		limit=4.0},
		ammo_price=0.0,
		weight=0.0,
		whitelist={Ghost=true,Demolition=true,Engineer=true,Medic=true,Heavy=true,Assault=true,
		Survivor=true},
		cmp=250.0,
		name="Marine",
		description="A formidable ally which will fight alongside you."
	},
	npc_vj_halo_unsc_spv3_keyes={
		secondary_ammo_price=0.0,
		price=500.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_keyes",
		entity_properties={
			x=50.0,type=3.0,
			z=15.0,
			yaw=0.0,
		limit=1.0},
		ammo_price=0.0,
		weight=0.0,
		whitelist={Ghost=true,Demolition=true,Engineer=true,Medic=true,Heavy=true,Assault=true,
		Survivor=true},
		cmp=250.0,
		name="Cpt. Keyes",
		description="Captain Keyes will raise the morale of nearby UNSC footsoldiers, raising\n their health by 35% and preventing crewman from cowering"
	},
	npc_vj_halo_unsc_spv3_chief={
		secondary_ammo_price=0.0,
		price=1000.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_chief",
		entity_properties={
			x=50.0,type=3.0,
			z=15.0,
			yaw=0.0,
		limit=1.0},
		ammo_price=0.0,
		weight=0.0,
		whitelist={Ghost=true,Demolition=true,Engineer=true,Medic=true,Heavy=true,Assault=true,
		Survivor=true},
		cmp=250.0,
		name="Master Chief",
		description="Master Chief is armed with a full arsenal of all grenade types,\n as well as a durable shield which can withstand hits and infection forms."
	},
	drc_ma5b={
		secondary_ammo_price=0.0,
		price=350.0,
		category="Rifle",
		class="drc_ma5b",
		entity_properties={type=1.0},
		ammo_price=70.0,
		weight=7.0,
		cmp=350.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="Ma5B Assault Rifle",
		description=""
	},
	drc_spnkr={
		secondary_ammo_price=0.0,
		price=600.0,
		category="Explosive",
		class="drc_spnkr",
		entity_properties={type=1.0},
		ammo_price=300.0,
		weight=7.0,
		cmp=600.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="SPNKr Rocket Launcher",
		description=""
	},
	drc_bruteshot={
		secondary_ammo_price=0.0,
		price=600.0,
		category="Explosive",
		class="drc_bruteshot",
		entity_properties={type=1.0},
		ammo_price=300.0,
		weight=7.0,
		cmp=600.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="Bruteshot",
		description=""
	},
	npc_vj_halo_for_spv3_aggressor_major={
		secondary_ammo_price=0.0,
		price=500.0,
		category="Special",
		class="npc_vj_halo_for_spv3_aggressor_major",
		entity_properties={
			x=50.0,type=3.0,
			limit=2.0,
			z=100.0,
		yaw=0.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=800.0,
		whitelist={Ghost=true,Demolition=true,Survivor=true,Medic=true,Heavy=true,Engineer=true,
		Assault=true},
		name="Forerunner Aggressor Major",
		description="These aggressors are equipped with even higher intensity heat-beam \nand upgraded gold armor plating, make them durable against major infestations."
	},
	npc_vj_halo_for_spv3_enforcer={
		secondary_ammo_price=0.0,
		price=1000.0,
		category="Special",
		class="npc_vj_halo_for_spv3_enforcer",
		entity_properties={
			x=50.0,type=3.0,
			limit=1.0,
			z=300.0,
		yaw=0.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=800.0,
		whitelist={Ghost=true,Demolition=true,Survivor=true,Medic=true,Heavy=true,Engineer=true,
		Assault=true},
		name="Forerunner Enforcer",
		description="These hefty Forerunner constructs wield dual flame rocket pods, capable of igniting an area on impact,\n and also wielding a set of dual needle pods which will is capable of shredding targets. \nIMPORTANT NOTE: Requires necesseary airspace to spawn and fly around in."
	},
	drc_m7={
		secondary_ammo_price=0.0,
		price=300.0,
		category="SMG",
		class="drc_m7",
		entity_properties={type=1.0},
		ammo_price=60.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=300.0,
		name="M7",
		description=""
	},
	weapon_vj_cov_spv3_plasma_nade={
		secondary_ammo_price=0.0,
		price=300.0,
		category="Equipment",
		class="weapon_vj_cov_spv3_plasma_nade",
		entity_properties={
			x=50.0,type=3.0,
			limit=5.0,
			z=15.0,
		yaw=0.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=300.0,
		whitelist={Ghost=true,Demolition=true,Assault=true,Medic=true,Heavy=true,Survivor=true,
		Engineer=true},
		name="Plasma Grenade",
		description="Takes a long time to explode but deals good damage.\n It can also stick to targets which can cause them to panick."
	},
	drc_plasma_rifle_brute={
		secondary_ammo_price=0.0,
		price=450.0,
		category="SMG",
		class="drc_plasma_rifle_brute",
		entity_properties={type=1.0},
		ammo_price=999999.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="Brute Plasma Rifle",
		description=""
	},
	drc_t51={
		secondary_ammo_price=0.0,
		price=350.0,
		category="Rifle",
		class="drc_t51",
		entity_properties={type=1.0},
		ammo_price=70.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=350.0,
		name="51 Particle Carbine",
		description=""
	},
	weapon_vj_cov_spv3_needler_nade={
		secondary_ammo_price=0.0,
		price=200.0,
		category="Equipment",
		class="weapon_vj_cov_spv3_needler_nade",
		entity_properties={
			x=50.0,type=3.0,
			limit=5.0,
			z=15.0,
		yaw=0.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=200.0,
		whitelist={Ghost=true,Demolition=true,Survivor=true,Medic=true,Heavy=true,Engineer=true,
		Assault=true},
		name="Needle Grenade",
		description="Spawns a bunch of covenant needles on spawn. Deadly in\n tight corridors. Can also be stuck to a target which would be extremely deadly."
	},
	drc_plasma_pistol={
		secondary_ammo_price=0.0,
		price=200.0,
		category="Pistol",
		class="drc_plasma_pistol",
		entity_properties={type=1.0},
		ammo_price=999999.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=200.0,
		name="Plasma Pistol",
		description=""
	},
	drc_m7s={
		secondary_ammo_price=0.0,
		price=300.0,
		category="SMG",
		class="drc_m7s",
		entity_properties={type=1.0},
		ammo_price=60.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=300.0,
		name="M7S",
		description=""
	},
	weapon_vj_unsc_spv3_frag_nade={
		secondary_ammo_price=0.0,
		price=250.0,
		category="Equipment",
		class="weapon_vj_unsc_spv3_frag_nade",
		entity_properties={
			x=50.0,type=3.0,
			limit=5.0,
			yaw=0.0,
		z=15.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=250.0,
		whitelist={Ghost=true,Demolition=true,Assault=true,Medic=true,Heavy=true,Survivor=true,
		Engineer=true},
		name="Frag Grenade",
		description="Good for bouncing around corners. Deals moderate damage."
	},
	npc_vj_halo_unsc_spv3_chief={
		secondary_ammo_price=0.0,
		price=1000.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_chief",
		entity_properties={
			x=50.0,type=3.0,
			yaw=0.0,
			z=15.0,
		limit=1.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=1000.0,
		whitelist={Ghost=true,Demolition=true,Assault=true,Medic=true,Heavy=true,Survivor=true,
		Engineer=true},
		name="Chief",
		description=""
	},
	npc_vj_halo_for_spv3_aggressor={
		secondary_ammo_price=0.0,
		price=250.0,
		category="Special",
		class="npc_vj_halo_for_spv3_aggressor",
		entity_properties={
			x=50.0,type=3.0,
			limit=4.0,
			yaw=0.0,
		z=100.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=500.0,
		whitelist={Ghost=true,Demolition=true,Engineer=true,Medic=true,Heavy=true,Assault=true,
		Survivor=true},
		name="Forerunner Aggressor",
		description="Equipped with a high-heat beam, these constructs will help deal with swaths of infestations."
	},
	drc_dmr={
		secondary_ammo_price=0.0,
		price=350.0,
		category="Rifle",
		class="drc_dmr",
		entity_properties={type=1.0},
		ammo_price=70.0,
		weight=7.0,
		cmp=350.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="DMR",
		description=""
	},
	npc_vj_halo_unsc_spv3_crewman={
		secondary_ammo_price=0.0,
		price=100.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_crewman",
		entity_properties={
			x=50.0,type=3.0,
			yaw=0.0,
			z=15.0,
		limit=5.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=100.0,
		whitelist={Ghost=true,Demolition=true,Assault=true,Medic=true,Heavy=true,Survivor=true,
		Engineer=true},
		name="Crewman",
		description="The most basic fodder a person could have. Low health, capable of \ndoing damage but will often wimp out of fights."
	},
	drc_spiker={
		secondary_ammo_price=0.0,
		price=300.0,
		category="SMG",
		class="drc_spiker",
		entity_properties={type=1.0},
		ammo_price=60.0,
		weight=7.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		cmp=300.0,
		name="Spiker",
		description=""
	},
	npc_vj_halo_unsc_spv3_rocket_pod={
		secondary_ammo_price=0.0,
		price=1000.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_rocket_pod",
		entity_properties={
			x=50.0,type=3.0,
			limit=2.0,
			z=15.0,
		yaw=0.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=1000.0,
		whitelist={Ghost=true,Demolition=true,Assault=true,Medic=true,Heavy=true,Survivor=true,
		Engineer=true},
		name="Ceiling Rocket Pod",
		description="A device which launches a set of 4 medium-damage \nmortars per volley. Requires a good distance to target for rocket to curve."
	},
	npc_vj_halo_unsc_spv3_stacker={
		secondary_ammo_price=0.0,
		price=750.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_stacker",
		entity_properties={
			x=50.0,type=3.0,
			z=15.0,
			yaw=0.0,
		limit=1.0},
		ammo_price=0.0,
		weight=0.0,
		whitelist={Ghost=true,Demolition=true,Survivor=true,Medic=true,Heavy=true,Engineer=true,
		Assault=true},
		cmp=750.0,
		name="Sgt. Stacker",
		description="Equipped with a Sniper Rifle and higher-grade armor, Marcus \nStacker will be able to help a great deal compared to your regular marine."
	},
	drc_m6d={
		secondary_ammo_price=0.0,
		price=200.0,
		category="Pistol",
		class="drc_m6d",
		entity_properties={type=1.0},
		ammo_price=40.0,
		weight=7.0,
		cmp=-1.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="M6D Magnum",
		description=""
	},
	npc_vj_halo_unsc_spv3_odst={
		secondary_ammo_price=0.0,
		price=500.0,
		category="Special",
		class="npc_vj_halo_unsc_spv3_odst",
		entity_properties={
			x=50.0,type=3.0,
			z=15.0,
			yaw=0.0,
		limit=2.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=500.0,
		whitelist={Ghost=true,Demolition=true,Engineer=true,Medic=true,Heavy=true,Assault=true,
		Survivor=true},
		name="ODST",
		description="Equipped with special weaponry and higher-grade armor, these \ntroops will pose a signfigant threat to the enemy."
	},
	weapon_vj_cov_spv3_cluster_nade={
		secondary_ammo_price=0.0,
		price=300.0,
		category="Equipment",
		class="weapon_vj_cov_spv3_cluster_nade",
		entity_properties={
			x=50.0,type=3.0,
			limit=5.0,
			yaw=0.0,
		z=15.0},
		ammo_price=0.0,
		weight=0.0,
		cmp=300.0,
		whitelist={Ghost=true,Demolition=true,Engineer=true,Medic=true,Heavy=true,Assault=true,
		Survivor=true},
		name="Cluster Grenade",
		description="Deals decent damage on impact and then spawns 5 \nchild nades afterwards in a medium-size area."
	},
	weapon_vj_cov_spv3_gravity_nade={
		secondary_ammo_price=0.0,
		price=400.0,
		category="Equipment",
		class="weapon_vj_cov_spv3_gravity_nade",
		entity_properties={
			x=50.0,type=3.0,
			limit=5.0,
			z=15.0,
		yaw=0.0},
		ammo_price=0.0,
		weight=0.0,
		whitelist={Ghost=true,Demolition=true,Engineer=true,Medic=true,Heavy=true,Assault=true,
		Survivor=true},
		cmp=400.0,
		name="Gravity Grenade",
		description="Pulls things towards it's landing point and violently explodes. Deadly around props (but also normally)."
	},
	drc_mauler={
		secondary_ammo_price=0.0,
		price=200.0,
		category="Pistol",
		class="drc_mauler",
		entity_properties={type=1.0},
		ammo_price=40.0,
		weight=7.0,
		cmp=200.0,
		whitelist={Ghost=true,Demolition=true,Medic=true,Heavy=true,Assault=true,Survivor=true},
		name="Mauler",
	description=""}
}






CONFIG.enemies = {
	grunt_maj3 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 3.0,
		class = "npc_vj_halo_cov_spv3_grunt_maj",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "grunt_maj3",
		weapon = "_gmod_default"
	},
	flood_marine7 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 7.0,
		class = "npc_vj_halo_flood_spv3_marine",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_marine7",
		weapon = ""
	},
	flood_carrier7 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 7.0,
		class = "npc_vj_halo_flood_spv3_carrier",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_carrier7",
		weapon = ""
	},
	brute_wchf10 = {
		health_scale = 1.0,
		weight = 0.25,
		wave = 10.0,
		class = "npc_vj_halo_cov_spv3_brute_wchf",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "brute_wchf10",
		weapon = "_gmod_default"
	},
	Skirm_min3 = {
		health_scale = 1.0,
		weight = 0.35,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_skirm_min",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 3.0,
		wave = 3.0,
		name = "Skirm_min3",
		weapon = "_gmod_default"
	},
	flood_carrier10 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 10.0,
		class = "npc_vj_halo_flood_spv3_carrier",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_carrier10",
		weapon = ""
	},
	jackal_mkm_maj9 = {
		health_scale = 1.0,
		weight = 0.5,
		wave = 9.0,
		class = "npc_vj_halo_cov_spv3_jackal_mkm_maj",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "jackal_mkm_maj9",
		weapon = "_gmod_default"
	},
	flood_jackal6 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 6.0,
		class = "npc_vj_halo_flood_spv3_jackal",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_jackal6",
		weapon = ""
	},
	Skirm_maj4 = {
		health_scale = 1.0,
		weight = 0.35,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_skirm_maj",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 3.0,
		wave = 4.0,
		name = "Skirm_maj4",
		weapon = "_gmod_default"
	},
	hunter_spc10 = {
		health_scale = 1.0,
		weight = 0.1,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_hunter_spc",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 10.0,
		name = "hunter_spc10",
		weapon = "_gmod_default"
	},
	elite_spc9 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_elite_spc",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 9.0,
		reward_scale = 4.0,
		name = "elite_spc9",
	damage_scale = 1.0},
	grunt_maj4 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 4.0,
		class = "npc_vj_halo_cov_spv3_grunt_maj",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "grunt_maj4",
		weapon = "_gmod_default"
	},
	flood_elite_ran8 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 8.0,
		class = "npc_vj_halo_flood_spv3_elite_ran",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_elite_ran8",
		weapon = ""
	},
	floo9 = {
		health_scale = 1.0,
		weight = 0.2,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_wolf",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 9.0,
		name = "floo9",
		weapon = "_gmod_default"
	},
	grunt_min1 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 1.0,
		class = "npc_vj_halo_cov_spv3_grunt_min",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "grunt_min1",
		weapon = "_gmod_default"
	},
	flood_elite5 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 5.0,
		class = "npc_vj_halo_flood_spv3_elite",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_elite5",
		weapon = ""
	},
	jackal_mkm_ult9 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_mkm_ult",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 9.0,
		reward_scale = 2.0,
		name = "jackal_mkm_ult9",
	damage_scale = 1.0},
	grunt_ult10 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 10.0,
		class = "npc_vj_halo_cov_spv3_grunt_ult",
		is_elite = false,
		weapon = "_gmod_default",
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "grunt_ult10",
	damage_scale = 1.0},
	elite_min1 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_elite_min",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 1.0,
		reward_scale = 4.0,
		name = "elite_min1",
	damage_scale = 1.0},
	brute_min2 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_brute_min",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 2.0,
		reward_scale = 4.0,
		name = "brute_min2",
	damage_scale = 1.0},
	flood_elite_ran10 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 10.0,
		class = "npc_vj_halo_flood_spv3_elite_ran",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_elite_ran10",
		weapon = ""
	},
	flood_marine5 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 5.0,
		class = "npc_vj_halo_flood_spv3_marine",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_marine5",
		weapon = ""
	},
	jackal_spc10 = {
		health_scale = 1.0,
		weight = 0.5,
		wave = 10.0,
		class = "npc_vj_halo_cov_spv3_jackal_spc",
		is_elite = false,
		weapon = "_gmod_default",
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "jackal_spc10",
	damage_scale = 1.0},
	grunt_min2 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 2.0,
		class = "npc_vj_halo_cov_spv3_grunt_min",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "grunt_min2",
		weapon = "_gmod_default"
	},
	flood_carrier6 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 6.0,
		class = "npc_vj_halo_flood_spv3_carrier",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_carrier6",
		weapon = ""
	},
	floo7 = {
		health_scale = 1.0,
		weight = 0.2,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_wolf",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 7.0,
		name = "floo7",
		weapon = "_gmod_default"
	},
	flood_brute5 = {
		health_scale = 1.0,
		weight = 1.0,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_brute",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 5.0,
		name = "flood_brute5",
		weapon = "_gmod_default"
	},
	jackal_min9 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_mkm_maj",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 9.0,
		reward_scale = 2.0,
		name = "jackal_min9",
	damage_scale = 1.0},
	flood_carrier8 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 8.0,
		class = "npc_vj_halo_flood_spv3_carrier",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_carrier8",
		weapon = ""
	},
	flood_brute8 = {
		health_scale = 1.0,
		weight = 1.0,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_brute",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 8.0,
		name = "flood_brute8",
		weapon = "_gmod_default"
	},
	brute_maj3 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_brute_maj",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 3.0,
		reward_scale = 4.0,
		name = "brute_maj3",
	damage_scale = 1.0},
	brute_ult9 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_brute_ult",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 9.0,
		reward_scale = 4.0,
		name = "brute_ult9",
	damage_scale = 1.0},
	elite_min2 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_elite_min",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 2.0,
		reward_scale = 4.0,
		name = "elite_min2",
	damage_scale = 1.0},
	flood_jackal7 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 7.0,
		class = "npc_vj_halo_flood_spv3_jackal",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_jackal7",
		weapon = ""
	},
	grunt_spc9 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 9.0,
		class = "npc_vj_halo_cov_spv3_grunt_spc",
		is_elite = false,
		weapon = "_gmod_default",
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "grunt_spc9",
	damage_scale = 1.0},
	elite_maj3 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_elite_maj",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 3.0,
		reward_scale = 4.0,
		name = "elite_maj3",
	damage_scale = 1.0},
	jackal_maj3 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_min",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 3.0,
		reward_scale = 2.0,
		name = "jackal_maj3",
	damage_scale = 1.0},
	jackal_min2 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_min",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 2.0,
		reward_scale = 2.0,
		name = "jackal_min2",
	damage_scale = 1.0},
	flood_elite6 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 6.0,
		class = "npc_vj_halo_flood_spv3_elite",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_elite6",
		weapon = ""
	},
	h4 = {
		health_scale = 1.0,
		weight = 0.1,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_hunter_min",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 4.0,
		reward_scale = 10.0,
		name = "h4",
	damage_scale = 1.0},
	floo8 = {
		health_scale = 1.0,
		weight = 0.2,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_wolf",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 8.0,
		name = "floo8",
		weapon = "_gmod_default"
	},
	flood_elite7 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 7.0,
		class = "npc_vj_halo_flood_spv3_elite",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_elite7",
		weapon = ""
	},
	flood_odst8 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 8.0,
		class = "npc_vj_halo_flood_spv3_odst",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_odst8",
		weapon = ""
	},
	jackal_ult9 = {
		health_scale = 1.0,
		weight = 0.5,
		wave = 9.0,
		class = "npc_vj_halo_cov_spv3_jackal_ult",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "jackal_ult9",
		weapon = "_gmod_default"
	},
	brute_maj4 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_brute_maj",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 4.0,
		reward_scale = 4.0,
		name = "brute_maj4",
	damage_scale = 1.0},
	jackal_mkm_min4 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_mkm_min",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 4.0,
		reward_scale = 2.0,
		name = "jackal_mkm_min4",
	damage_scale = 1.0},
	elite_zel10 = {
		health_scale = 1.0,
		weight = 0.25,
		wave = 10.0,
		class = "npc_vj_halo_cov_spv3_elite_hg_zel",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "elite_zel10",
		weapon = "_gmod_default"
	},
	jackal_spc9 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_spc",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 9.0,
		reward_scale = 2.0,
		name = "jackal_spc9",
	damage_scale = 1.0},
	flood_odst10 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 10.0,
		class = "npc_vj_halo_flood_spv3_odst",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_odst10",
		weapon = ""
	},
	elite_maj4 = {
		health_scale = 1.0,
		weight = 0.25,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_elite_maj",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 4.0,
		reward_scale = 4.0,
		name = "elite_maj4",
	damage_scale = 1.0},
	elite_hg_zel10 = {
		health_scale = 1.0,
		weight = 0.25,
		wave = 10.0,
		class = "npc_vj_halo_cov_spv3_elite_hg_zel",
		is_elite = false,
		weapon = "_gmod_default",
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "elite_hg_zel10",
	damage_scale = 1.0},
	flood_brute9 = {
		health_scale = 1.0,
		weight = 1.0,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_brute",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 9.0,
		name = "flood_brute9",
		weapon = "_gmod_default"
	},
	flood_jackal8 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 8.0,
		class = "npc_vj_halo_flood_spv3_jackal",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_jackal8",
		weapon = ""
	},
	flood_brute10 = {
		health_scale = 1.0,
		weight = 1.0,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_brute",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 10.0,
		name = "flood_brute10",
		weapon = "_gmod_default"
	},
	floo10 = {
		health_scale = 1.0,
		weight = 0.2,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_wolf",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 10.0,
		name = "floo10",
		weapon = "_gmod_default"
	},
	flood_marine6 = {
		health_scale = 1.0,
		weight = 1.0,
		wave = 6.0,
		class = "npc_vj_halo_flood_spv3_marine",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_marine6",
		weapon = ""
	},
	flood_brute7 = {
		health_scale = 1.0,
		weight = 1.0,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_brute",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 7.0,
		name = "flood_brute7",
		weapon = "_gmod_default"
	},
	jackal_mkm_ult10 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_mkm_ult",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 10.0,
		reward_scale = 2.0,
		name = "jackal_mkm_ult10",
	damage_scale = 1.0},
	flood_brute6 = {
		health_scale = 1.0,
		weight = 1.0,
		model_scale = 1.0,
		class = "npc_vj_halo_flood_spv3_brute",
		is_elite = 0.0,
		damage_scale = 1.0,
		spawn_limit = 0.0,
		reward_scale = 1.0,
		wave = 6.0,
		name = "flood_brute6",
		weapon = "_gmod_default"
	},
	jackal_maj4 = {
		health_scale = 1.0,
		weight = 0.5,
		model_scale = 1.0,
		class = "npc_vj_halo_cov_spv3_jackal_maj",
		is_elite = 0.0,
		weapon = "_gmod_default",
		spawn_limit = 0.0,
		wave = 4.0,
		reward_scale = 2.0,
		name = "jackal_maj4",
	damage_scale = 1.0},
	flood_jackal10 = {
		health_scale = 1.0,
		weight = 0.2,
		wave = 10.0,
		class = "npc_vj_halo_flood_spv3_jackal",
		is_elite = false,
		damage_scale = 1.0,
		model_scale = 1.0,
		reward_scale = 1.0,
		name = "flood_jackal10",
	weapon = ""}
}